SQLALCHEMY_DATABASE_URI=postgresql://localhost/indianbanks
export SQLALCHEMY_DATABASE_URI
APP_SETTINGS=config.DevelopmentConfig
export APP_SETTINGS
SECRET_KEY=hcgast23512asd78283742bdfiwebf
export SECRET_KEY